version: "3"

services:
  api:
    build: .
    env_file:
      - .env
    command: python -m src.main
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  broker:
    image: eclipse-mosquitto
    env_file:
      - .env
    ports:
      - ${MOSQUITTO_PORT}:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/password_file:/mosquitto/config/password_file
      - ./mosquitto/data:/mosquitto/data

volumes:
  postgres-data:
