version: "3"

services:
  api:
    build: .
    env_file:
      - .env
    depends_on:
      - database
      - broker
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
  broker:
    image: eclipse-mosquitto
    env_file:
      - .env
    ports:
      - ${MOSQUITTO_PORT}:1883
    volumes:
      - ./mosquitto.conf/:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
