apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: noise
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 86400000 # 1 day
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: setup
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000 # 1 week
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: shutdown
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000 # 1 week
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: notification
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000 # 1 day
